[2021-06-27 05:55:22,409] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: csv_json_merge.processed_csv_check 2021-06-26T00:00:00+00:00 [queued]>
[2021-06-27 05:55:22,416] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: csv_json_merge.processed_csv_check 2021-06-26T00:00:00+00:00 [queued]>
[2021-06-27 05:55:22,416] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2021-06-27 05:55:22,416] {taskinstance.py:867} INFO - Starting attempt 1 of 2
[2021-06-27 05:55:22,416] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2021-06-27 05:55:22,426] {taskinstance.py:887} INFO - Executing <Task(BashOperator): processed_csv_check> on 2021-06-26T00:00:00+00:00
[2021-06-27 05:55:22,429] {standard_task_runner.py:53} INFO - Started process 4701 to run task
[2021-06-27 05:55:22,477] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: csv_json_merge.processed_csv_check 2021-06-26T00:00:00+00:00 [running]> ip-172-31-21-147.ec2.internal
[2021-06-27 05:55:22,489] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2021-06-27 05:55:22,491] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmpdLJszp/processed_csv_checkgSqAWK
[2021-06-27 05:55:22,491] {bash_operator.py:115} INFO - Running command: shasum ~/airflow/processed/csv_data/csv*
[2021-06-27 05:55:22,497] {bash_operator.py:122} INFO - Output:
[2021-06-27 05:55:22,519] {bash_operator.py:126} INFO - 9885de5e78a4039f00129255bfe5708475acddc3  /home/ubuntu/airflow/processed/csv_data/csv_processed_2021-06-27.csv
[2021-06-27 05:55:22,519] {bash_operator.py:130} INFO - Command exited with return code 0
[2021-06-27 05:55:22,526] {taskinstance.py:1048} INFO - Marking task as SUCCESS.dag_id=csv_json_merge, task_id=processed_csv_check, execution_date=20210626T000000, start_date=20210627T055522, end_date=20210627T055522
[2021-06-27 05:55:32,407] {logging_mixin.py:112} INFO - [2021-06-27 05:55:32,407] {local_task_job.py:103} INFO - Task exited with return code 0
