[2021-06-27 05:02:32,707] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: csv_data_ingesation.csv_src_cleanup 2021-06-27T04:59:53.982771+00:00 [queued]>
[2021-06-27 05:02:32,718] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: csv_data_ingesation.csv_src_cleanup 2021-06-27T04:59:53.982771+00:00 [queued]>
[2021-06-27 05:02:32,718] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2021-06-27 05:02:32,718] {taskinstance.py:867} INFO - Starting attempt 1 of 2
[2021-06-27 05:02:32,718] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2021-06-27 05:02:32,727] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): csv_src_cleanup> on 2021-06-27T04:59:53.982771+00:00
[2021-06-27 05:02:32,730] {standard_task_runner.py:53} INFO - Started process 2461 to run task
[2021-06-27 05:02:32,779] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: csv_data_ingesation.csv_src_cleanup 2021-06-27T04:59:53.982771+00:00 [running]> ip-172-31-21-147.ec2.internal
[2021-06-27 05:02:32,792] {python_operator.py:114} INFO - Done. Returned value was: None
[2021-06-27 05:02:32,795] {taskinstance.py:1048} INFO - Marking task as SUCCESS.dag_id=csv_data_ingesation, task_id=csv_src_cleanup, execution_date=20210627T045953, start_date=20210627T050232, end_date=20210627T050232
[2021-06-27 05:02:42,694] {logging_mixin.py:112} INFO - [2021-06-27 05:02:42,694] {local_task_job.py:103} INFO - Task exited with return code 0
