[2021-06-27 06:16:23,350] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: csv_json_merge.json_processed_src_cleanup 2021-06-27T06:13:24.265756+00:00 [queued]>
[2021-06-27 06:16:23,361] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: csv_json_merge.json_processed_src_cleanup 2021-06-27T06:13:24.265756+00:00 [queued]>
[2021-06-27 06:16:23,361] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2021-06-27 06:16:23,361] {taskinstance.py:867} INFO - Starting attempt 1 of 2
[2021-06-27 06:16:23,361] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2021-06-27 06:16:23,372] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): json_processed_src_cleanup> on 2021-06-27T06:13:24.265756+00:00
[2021-06-27 06:16:23,375] {standard_task_runner.py:53} INFO - Started process 7394 to run task
[2021-06-27 06:16:23,425] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: csv_json_merge.json_processed_src_cleanup 2021-06-27T06:13:24.265756+00:00 [running]> ip-172-31-21-147.ec2.internal
[2021-06-27 06:16:23,438] {python_operator.py:114} INFO - Done. Returned value was: None
[2021-06-27 06:16:23,442] {taskinstance.py:1048} INFO - Marking task as SUCCESS.dag_id=csv_json_merge, task_id=json_processed_src_cleanup, execution_date=20210627T061324, start_date=20210627T061623, end_date=20210627T061623
[2021-06-27 06:16:33,344] {logging_mixin.py:112} INFO - [2021-06-27 06:16:33,343] {local_task_job.py:103} INFO - Task exited with return code 0
