[2021-05-16 05:30:01,342] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: json_data_ingesation.process_json 2021-05-16T05:28:11.412236+00:00 [queued]>
[2021-05-16 05:30:01,351] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: json_data_ingesation.process_json 2021-05-16T05:28:11.412236+00:00 [queued]>
[2021-05-16 05:30:01,352] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 05:30:01,352] {taskinstance.py:867} INFO - Starting attempt 1 of 2
[2021-05-16 05:30:01,352] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 05:30:01,362] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): process_json> on 2021-05-16T05:28:11.412236+00:00
[2021-05-16 05:30:01,364] {standard_task_runner.py:53} INFO - Started process 2256 to run task
[2021-05-16 05:30:01,412] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: json_data_ingesation.process_json 2021-05-16T05:28:11.412236+00:00 [running]> ip-172-31-21-147.ec2.internal
[2021-05-16 05:30:01,424] {taskinstance.py:1128} ERROR - initial_value must be unicode or None, not str
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/dags/process_utils.py", line 17, in process_json
    series = pd.read_json(StringIO(row), typ='series')
TypeError: initial_value must be unicode or None, not str
[2021-05-16 05:30:01,424] {taskinstance.py:1151} INFO - Marking task as UP_FOR_RETRY
[2021-05-16 05:30:11,330] {logging_mixin.py:112} INFO - [2021-05-16 05:30:11,330] {local_task_job.py:103} INFO - Task exited with return code 1
